export const blogArticles = [
  {
    slug: "are-scratch-and-dent-appliances-worth-it",
    title: "Are Scratch and Dent Appliances Worth It? The Complete Guide",
    metaTitle: "Are Scratch and Dent Appliances Worth It? (2026 Guide)",
    metaDescription: "Find out if scratch and dent appliances are worth buying. Learn about typical savings of 30-70%, warranty coverage, what to inspect, and when to buy or avoid.",
    publishDate: "2026-03-02",
    keywords: "scratch and dent appliances worth it, are scratch and dent appliances good, should I buy scratch and dent appliances",
  },
  {
    slug: "how-to-save-on-refrigerators-washers-dryers",
    title: "How to Save 30-70% on Refrigerators, Washers & Dryers",
    metaTitle: "How to Save 30-70% on Appliances (6 Proven Ways)",
    metaDescription: "Discover 6 proven ways to save 30-70% on refrigerators, washers, and dryers. From scratch & dent stores to holiday sales, here's how smart shoppers buy appliances for less.",
    publishDate: "2026-03-02",
    keywords: "how to save on appliances, cheap appliances near me, discount appliance stores",
  },
  {
    slug: "scratch-and-dent-vs-open-box-vs-refurbished",
    title: "Scratch and Dent vs. Open Box vs. Refurbished: What's the Difference?",
    metaTitle: "Scratch & Dent vs Open Box vs Refurbished Appliances",
    metaDescription: "Confused by scratch and dent, open box, and refurbished appliances? Learn the key differences in warranty, pricing, risk, and quality to pick the right option for you.",
    publishDate: "2026-03-02",
    keywords: "scratch and dent vs open box, refurbished appliances vs scratch and dent, open box appliances",
  },
  {
    slug: "best-time-to-buy-appliances",
    title: "Best Time to Buy Appliances in 2026 (Month-by-Month Guide)",
    metaTitle: "Best Time to Buy Appliances in 2026 (Monthly Guide)",
    metaDescription: "Month-by-month guide to the best times to buy appliances in 2026. Learn when refrigerators, washers & dryers go on sale — and how to save 30-70% year-round.",
    publishDate: "2026-03-02",
    keywords: "best time to buy appliances, when do appliances go on sale, best time to buy refrigerator",
  },
  {
    slug: "scratch-and-dent-appliances-near-me",
    title: "Scratch and Dent Appliances Near Me: How to Find the Best Deals in Your Area",
    metaTitle: "Scratch and Dent Appliances Near Me (Find Stores)",
    metaDescription: "Find scratch and dent appliance stores near you. Learn how to evaluate local dealers, what to ask before visiting, and red flags to avoid. 728+ verified stores listed.",
    publishDate: "2026-03-02",
    keywords: "scratch and dent appliances near me, discount appliances near me, appliance outlet near me",
  },
  {
    slug: "how-to-inspect-scratch-and-dent-appliances",
    title: "How to Inspect a Scratch and Dent Appliance Before Buying (Complete Checklist)",
    metaTitle: "How to Inspect Scratch & Dent Appliances (Checklist)",
    metaDescription: "Step-by-step checklist for inspecting scratch and dent appliances before buying. Covers exterior, interior, functional tests, warranty, and return policy verification.",
    publishDate: "2026-03-02",
    keywords: "scratch and dent appliance inspection, what to check before buying appliances, how to buy scratch and dent appliances",
  },
  {
    slug: "samsung-scratch-and-dent-deals",
    title: "Samsung Scratch and Dent Deals: Where to Find Discounted Samsung Appliances",
    metaTitle: "Samsung Scratch and Dent Deals (Save 30-70%)",
    metaDescription: "Find discounted Samsung appliances at scratch and dent stores near you. Same technology, full warranty, 30-70% off retail. 728+ verified stores across 51 states.",
    publishDate: "2026-03-02",
    keywords: "Samsung scratch and dent, discount Samsung appliances, Samsung appliance outlet",
  },
  {
    slug: "lg-scratch-and-dent-deals",
    title: "LG Scratch and Dent Deals: Where to Find Discounted LG Appliances",
    metaTitle: "LG Scratch and Dent Deals (Save 30-70%)",
    metaDescription: "Find discounted LG appliances at scratch and dent stores. InstaView fridges, TurboWash washers, QuadWash dishwashers — 30-70% off. 728+ verified stores listed.",
    publishDate: "2026-03-02",
    keywords: "LG scratch and dent, discount LG appliances, LG appliance outlet",
  },
  {
    slug: "whirlpool-scratch-and-dent-deals",
    title: "Whirlpool Scratch and Dent Deals: Where to Find Discounted Whirlpool Appliances",
    metaTitle: "Whirlpool Scratch and Dent Deals (Save 30-70%)",
    metaDescription: "Find discounted Whirlpool, Maytag, KitchenAid & Amana appliances at scratch and dent stores. The most widely available brand means more inventory and better deals.",
    publishDate: "2026-03-02",
    keywords: "Whirlpool scratch and dent, discount Whirlpool appliances, Whirlpool appliance outlet",
  },
  {
    slug: "best-scratch-and-dent-stores-atlanta",
    title: "Best Scratch and Dent Appliance Stores in Atlanta, GA",
    metaTitle: "Best Scratch & Dent Appliance Stores in Atlanta",
    metaDescription: "Find the best scratch and dent appliance stores in Atlanta, GA. Save 30-70% on refrigerators, washers & dryers. Browse verified Atlanta-area stores now.",
    publishDate: "2026-03-03",
    keywords: "scratch and dent appliances Atlanta, discount appliances Atlanta GA, appliance outlet Atlanta",
  },
  {
    slug: "best-scratch-and-dent-stores-houston",
    title: "Best Scratch and Dent Appliance Stores in Houston, TX",
    metaTitle: "Best Scratch & Dent Appliance Stores in Houston",
    metaDescription: "Find the best scratch and dent appliance stores in Houston, TX. Save 30-70% on refrigerators, washers & dryers. Browse verified Houston-area stores now.",
    publishDate: "2026-03-03",
    keywords: "scratch and dent appliances Houston, discount appliances Houston TX, appliance outlet Houston",
  },
  {
    slug: "best-scratch-and-dent-stores-phoenix",
    title: "Best Scratch and Dent Appliance Stores in Phoenix, AZ",
    metaTitle: "Best Scratch & Dent Appliance Stores in Phoenix",
    metaDescription: "Find the best scratch and dent appliance stores in Phoenix, AZ. Save 30-70% on refrigerators, washers & dryers. Browse verified Phoenix-area stores now.",
    publishDate: "2026-03-03",
    keywords: "scratch and dent appliances Phoenix, discount appliances Phoenix AZ, appliance outlet Phoenix",
  },
];
